console.log(
  [
    "You will not be disappointed",
    "Show your appreciation",
    "Your actions will improve things",
    "Don't bet on it",
    "Adopt an adventurous attitude",
    "Follow the advice of experts",
    "You could find yourself unable to",
    "Compromise",
    "Focus on your home life",
    "Investigate and then enjoy it",
    "Definitely",
    "Only do it once",
    "You may have opposition",
    "It will remain unpredictable",
    "You'll need to take the initiative",
    "Consider it an opportunity",
    "Be deliberate",
    "Absolutely not",
    "Explore it with playful curiosity",
    "Perhaps, when you're older",
    "Be delightfully sure of it",
    "Better to wait",
    "Reprioritize what is important",
    "It seems assured",
    "Create more space for it",
    "Do it early",
    "Keep it to yourself",
    "Allow yourself to rest first",
    "It is sensible",
    "You'll have to make it up as you go",
    "Startling events may occur as a result",
    "The answer may come to you in another",
    "Language",
    "You will need to accommodate",
    "Doubt it",
    "It will bring good luck",
    "It may be challenging, but you will find",
    "Value in it",
    "Be patient",
    "You will find out everything you'll need",
    "To know",
    "There is a substantial link to another",
    "Situation",
    "Watch and see what happens",
    "You know better now than ever before",
    "It will affect how others see you",
    "Reconsider your approach",
    "You'll be happy you did",
    "Get it in writing",
    "Unfavorable at this time",
    "It is not something to be taken lightly",
    "Upgrade in any way you can",
    "If you do as you're told",
    "If it's done well; if not, don't do it at all",
    "Don't ask for any more at this time",
    "Avoid the first solution",
    "You'll get the final word",
    "Proceed at a more relaxed pace",
    "The best solution may not be the obvious",
    "One",
    "Remain flexible",
    "Respect the rules",
    "Take the lead",
    "Choose your words thoughtfully",
    "You may be hanging on to an outdated",
    "Ideal",
    "There may be a struggle",
    "You'll have the enthusiasm you'll need",
    "Provided you say “thank you”",
    "Enjoy the experience",
    "Approach cautiously",
    "Be your own best advocate",
    "Be happy for another",
    "Pay attention to the details",
    "Watch your step as you go",
    "Speak up about it",
    "Don't hesitate",
    "This is a good time to make a new plan",
    "Move on",
    "A strong commitment will achieve good",
    "Results",
    "It may not be logical",
    "There is no guarantee",
    "The circumstances could change very",
    "Quickly",
    "Don't get caught up in your emotions",
    "Shift your focus",
    "It is significant",
    "Reprioritize what is important",
    "Make a list of why not",
    "Don't wait",
    "Take your time",
    "There is good reason to be optimistic",
    "It is something you won't forget",
    "Seek out more options",
    "Follow through on your obligations",
    "Deal with it later",
    "Reveal your thoughts to a trusted",
    "Confidante",
    "Follow someone else's lead",
    "You could find yourself unable to",
    "Compromise",
    "Make a list of why",
    "Take a chance",
    "Your actions will improve things",
    "Ask for help",
    "Know when it's time to go",
    "Accept a change to your routine",
    "You'll need to take the initiative",
    "You'll have to compromise",
    "You need more information",
    "Trust your original thought",
    "Seek out the path of least resistance",
    "It will create a stir",
    "You'll overcome any obstacles",
    "It would be better to focus on your work",
    "It will be a pleasure",
    "Be more generous",
    "Bet on it",
    "Good things are seeking you out",
    "Don't leave room for regret",
    "Make a contribution",
    "Mishaps are highly probable",
    "Press for closure",
    "Realize that too many choices can be as",
    "Difficult as too few",
    "Yes",
    "Listen carefully; then you will know",
    "The answer is in your backyard",
    "Laugh about it",
    "Let your emotions guide you",
    "Others will depend on your choices",
    "Let it go",
    "It's time for you to go",
    "Don't be distracted",
    "Give it all you've got",
    "You don't really care",
    "You'll need to consider other ways",
    "A year from now it won't matter",
    "Follow the advice of experts",
    "It could be extraordinary",
    "Count to ten; ask again",
    "Act as though it is already real",
    "Setting priorities will be a necessary part",
    "Of the process",
    "Use your imagination",
    "It's gonna be great",
    "To ensure the best decision, be calm",
    "Wait",
    "You'll have to make it up as you go",
    "Follow the directions",
    "Unquestionably",
    "Of course",
    "Look for what may be hidden",
    "You know better now than ever before",
    "Trust your intuition",
    "Don't miss an opportunity",
    "Ask your father",
    "Ask your mother",
    "Perhaps, when you're older",
    "Maybe",
    "Finish something else first",
    "You may have opposition",
    "You are too close to see",
    "The situation is unclear",
    "A substantial effort will be required",
    "Allow yourself to rest first",
    "The chance will not come again soon",
    "The answer may come to you in another",
    "Language",
    "Reconsider your approach",
    "It would be inadvisable",
    "There is a small price to pay",
    "Wait for a better offer",
    "Settle it soon",
    "Remain objective",
    "Yes, but don't force it",
    "Get a clearer view",
    "Be delightfully sure of it",
    "Now you can",
    "Provided you say “thank you”",
    "Don't overdo it",
    "It will sustain you",
    "It could cost you",
    "Adopt an adventurous attitude",
    "It is sure to make things interesting",
    "Be practical",
    "Are you ready?",
    "Save your energy",
    "Pay attention to the details",
    "It is certain",
    "It is uncertain",
    "The outcome will be positive",
    "You may have to drop other things",
    "Don't be concerned",
    "Prepare for the unexpected",
    "Tell someone what it means to you",
    "Whatever you do, the results will be",
    "Lasting",
    "Keep an open mind",
    "It's a good time to make plans",
    "It may be ambitious, but you will find",
    "Value in it",
    "It is worth the trouble",
    "You'll overcome any obstacles",
    "Related issues may surface",
    "You are sure to have support",
    "Assistance would make your progress a",
    "Success",
    "Collaboration will be the key",
    "Seek out more options",
    "Take charge",
    "It cannot fail",
    "You must act now",
    "Respect the rules",
    "Gentle persistence will pay off",
    "You could be disappointed",
    "It may already be a done deal",
    "Follow through with your good",
    "Intentions",
    "Take more time to decide",
    "Follow through on your obligations",
    "Don't be pressured into acting too quickly",
    "Don't ignore the obvious",
    "Others will respect your choices",
    "Don't be too practical",
    "Be a good role model",
    "It's not worth a struggle",
    "Listen carefully; then you will know",
    "Don't forget to have fun",
    "Don't doubt it",
    "A strong commitment will achieve good",
    "Results",
    "Try a more unlikely solution",
    "Leave behind old solutions",
    "Keep it to yourself",
    "Watch your step as you go",
    "Explore it with playful curiosity",
    "Don't be too demanding",
    "Don't leave room for regret",
    "Act as though it is already real",
    "It isn't personal",
    "Be persistent",
    "Choose what will make you happy",
    "Don't let money decide it",
    "It will work itself out",
    "If it's too difficult, maybe it's not yours",
    "It could mean that you may have to do",
    "Something that you've never done",
    "Decide where you want to be and head in",
    "That direction",
    "Cast your net wider",
    "Make no assumptions",
    "Respect the fundamentals",
    "Be resourceful",
    "Find more time",
    "Nothing will compare",
    "It will be an opportunity",
    "Don't give up your right to wait",
    "Be deliberate",
    "Why is it important to you?",
    "Don't let the moment pass",
    "You'll get what you settle for",
    "Choose whatever will help you to grow",
    "Be kind",
    "Realize that too many choices can be as",
    "Difficult as too few",
    "Take a chance",
    "You will have everything necessary for",
    "Your success",
    "Others may not approve",
    "You'll have the strength you'll need",
    "Initiate an adventure",
    "Be tactful",
    "You'll need to consider other ways",
    "Figure out a way",
    "It could be a matter of pride",
    "Pursue more variety",
    "Don't get caught up in your emotions",
    "Pitch in whatever you can",
    "Arrive early",
    "No matter what",
    "You are too close to see",
    "Yes",
    "Don't take a chance",
    "It is not something to be taken lightly",
    "Be content to leave well enough alone",
    "Too much attention is on the details",
    "Keep it light",
    "Get more sleep",
    "Reconsider another possibility",
    "It may not be logical",
    "The answer is in your backyard",
    "Make a contribution",
    "Use your imagination",
    "Know no limitations",
    "Build something bigger",
    "Aim higher",
    "Take it in stride",
    "Be a good sport",
    "Take the lead",
    "There is a small price to pay",
    "Don't be too critical",
    "Put your feelings in the right place",
    "Identify what matters about it",
    "How things turn out will depend on you",
    "Look for what may be hidden",
    "Let your emotions guide you",
    "Reveal your thoughts to a trusted",
    "Confidante",
    "Take a closer look",
    "Don't be concerned",
    "You can do this on your own",
    "Ask for help",
    "Create more space for it",
    "Divert your attention",
    "What do you want?",
    "Do your best to set the standard",
    "There is good reason to be optimistic",
    "Don't be distracted",
    "Enjoy a new setting",
    "You will need to accommodate",
    "Remain objective",
    "Tell someone what it means to you",
    "Consider it an opportunity",
    "Seek out the path of least resistance",
    "Good things are seeking you out",
    "It won't matter when you do, but that you",
    "Do",
    "You may be hanging on to an outdated",
    "Ideal",
    "It'll change your luck",
    "Don't resist",
    "Follow the directions",
    "The best solution may be the obvious one",
    "Don't be too cautious",
    "You may regret it",
    "Is it important to you?",
    "Choose your words carefully",
    "Limit the options",
    "Focus your attention",
    "Shouldn't you be outside playing?",
    "Would it be a pleasure?",
    "Be on time",
    "Ask your father",
    "Ask your mother",
    "Take your time",
    "Yes, but don't force it",
    "There is more to know",
    "Find out the facts",
    "Not if you're alone",
    "Uncover more details",
    "Your heart isn't in it",
    "Be happy for another",
    "You are favored",
    "Never",
    "A year from now it won't matter",
    "Are you ready?",
    "You must",
    "No",
    "Conserve your resources",
    "Be a good role model",
    "Negotiate a better deal",
    "Favor the good things",
    "Don't let it be ruined by reason",
    "Sleep on it",
    "Do your best",
    "It is not significant",
    "You have so much to offer",
    "Know what's important to you",
    "You deserve the best",
    "Better things are seeking you out",
    "It's up to you",
    "Choose what makes you happy",
    "Let your heart lead the way",
    "Don't get caught up in the details",
  ][Math.floor(Math.random() * 376)],
);
